# Novo doba

_Predavanje na otvorenju Centra izvrsnosti iz matematike Splitsko-dalmatinske županije_

Ivan Slapničar, Sveučilište u Splitu, FESB



## Poruke

Lako - Teško (u svemu!)

Sada - doba __pretraživanja__ -> _matematika_

Dolazi - doba __preporuka__  -> _matematika_

(BigData, nova tehnologija)


## Lako - teško

vaganje:  1 _kg_  -> 1 _kg_ $\pm$ 0.000000001 _kg_

trčanje: 100 _m_ -> 42,195 _m_ ili 100 _m_ < 10 _sek_

zadaci iz matematike: test za CI -> državno natjecanje ([2016](http://natjecanja.math.hr/drzavno-natjecanje/drzavno-2016/) ili [sve](http://www.antonija-horvatek.from.hr/natjecanja-iz-matematike/zadaci-SS.htm)), ili [matematička olimpijada](http://www.imo-official.org/)

## Doba pretraživanja

google (i ostali)


* [50 milijardi stranica](http://www.worldwidewebsize.com/), [3.5 milijarde pretraživanja dnevno](http://www.internetlivestats.com/google-search-statistics/)
* __PageRank__
* povijest, kontekst - cookies, spremanje podataka (o vama), [200+ parametara](http://backlinko.com/google-ranking-factors)

## PageRank

* Teorija grafova i linearna algebra
* [C, Moler, Google PageRank][Mol11]


[Mol11]: https://www.mathworks.com/moler/exm/chapters/pagerank.pdf "C, Moler, 'Google PageRank', mathWorks, 2011."


In [26]:
i = vec([ 2 6 3 4 4 5 6 1 1])
j = vec([ 1 1 2 2 3 3 3 4 6])
G=sparse(i,j,1.0)

6×6 sparse matrix with 9 Float64 nonzero entries:
	[2, 1]  =  1.0
	[6, 1]  =  1.0
	[3, 2]  =  1.0
	[4, 2]  =  1.0
	[4, 3]  =  1.0
	[5, 3]  =  1.0
	[6, 3]  =  1.0
	[1, 4]  =  1.0
	[1, 6]  =  1.0

In [27]:
full(G)

6×6 Array{Float64,2}:
 0.0  0.0  0.0  1.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0

Na graf primijenimo slučajnu šetnju (_random walk_)- vjerojatnost da pratimo bilo koji link je jednaka:

In [28]:
c=sum(G,1)
n=size(G,1)
for j=1:n
    if c[j]>0
        G[:,j]=G[:,j]/c[j]
    end
end
full(G)

6×6 Array{Float64,2}:
 0.0  0.0  0.0       1.0  0.0  1.0
 0.5  0.0  0.0       0.0  0.0  0.0
 0.0  0.5  0.0       0.0  0.0  0.0
 0.0  0.5  0.333333  0.0  0.0  0.0
 0.0  0.0  0.333333  0.0  0.0  0.0
 0.5  0.0  0.333333  0.0  0.0  0.0

* $p$: vjerojatnost da pratimo neki link
* $1-p$:  je vjerojatnost da odemo na neku drugu slučajnu stranicu
* google koristi $p=0.85$ ?

In [29]:
p=0.85
z = ((1-p)*(c.!=0) + (c.==0))/n
A=p*G+ones(n)*z

6×6 Array{Float64,2}:
 0.025  0.025  0.025     0.875  0.166667  0.875
 0.45   0.025  0.025     0.025  0.166667  0.025
 0.025  0.45   0.025     0.025  0.166667  0.025
 0.025  0.45   0.308333  0.025  0.166667  0.025
 0.025  0.025  0.308333  0.025  0.166667  0.025
 0.45   0.025  0.308333  0.025  0.166667  0.025

Pokrenimo slučajnu šetnju od vektora $x_0=\begin{bmatrix} 1/n \\ 1/n \\ \vdots \\ 1/n \end{bmatrix}$.

Sljedeći vektori u nizu su 

$$
x_1=A\cdot x_0 \\
x_2=A\cdot x_1 \\
x_3=A\cdot x_2\\
\vdots
$$

Kada se algoritam stabilizira, odnosno kada je 

$$
A\cdot x\approx x,
$$

tada je element vektora $x[i]$ __rang stranice__ $i$.

In [13]:
function myPageRank(G::SparseMatrixCSC{Float64,Int64},steps::Int)
    p=0.85
    c=sum(G,1)/p
    n=size(G,1)
    for i=1:n
        G.nzval[G.colptr[i]:G.colptr[i+1]-1]./=c[i]
    end
    e=ones(n)
    x=e/n
    z = vec(((1-p)*(c.!=0) + (c.==0))/n)
    for j=1:steps
        x=G*x+(z⋅x)
    end
    x/norm(x,1)
end

myPageRank (generic function with 1 method)

In [15]:
myPageRank(G,15)

6-element Array{Float64,1}:
 0.321024 
 0.170538 
 0.106596 
 0.136795 
 0.0643103
 0.200737 

### [Stanford web graph](http://snap.stanford.edu/data/web-Stanford.html)

Malo veći testni problem.

In [18]:
W=readdlm("web-Stanford.txt",Int)

2312497×2 Array{Int64,2}:
      1    6548
      1   15409
   6548   57031
  15409   13102
      2   17794
      2   25202
      2   53625
      2   54582
      2   64930
      2   73764
      2   84477
      2   98628
      2  100193
      ⋮        
 281849  165189
 281849  177014
 281849  226290
 281849  243180
 281849  244195
 281849  247252
 281849  281568
 281865  186750
 281865  225872
 281888  114388
 281888  192969
 281888  233184

In [19]:
S=sparse(W[:,2],W[:,1],1.0)

281903×281903 sparse matrix with 2312497 Float64 nonzero entries:
	[6548  ,      1]  =  1.0
	[15409 ,      1]  =  1.0
	[17794 ,      2]  =  1.0
	[25202 ,      2]  =  1.0
	[53625 ,      2]  =  1.0
	[54582 ,      2]  =  1.0
	[64930 ,      2]  =  1.0
	[73764 ,      2]  =  1.0
	[84477 ,      2]  =  1.0
	[98628 ,      2]  =  1.0
	⋮
	[168703, 281902]  =  1.0
	[180771, 281902]  =  1.0
	[266504, 281902]  =  1.0
	[275189, 281902]  =  1.0
	[44103 , 281903]  =  1.0
	[56088 , 281903]  =  1.0
	[90591 , 281903]  =  1.0
	[94440 , 281903]  =  1.0
	[216688, 281903]  =  1.0
	[256539, 281903]  =  1.0
	[260899, 281903]  =  1.0

In [20]:
@time x100=myPageRank(S,100);

  1.491916 seconds (846.80 k allocations: 542.598 MB, 11.86% gc time)


In [21]:
x101=myPageRank(S,101)
maxabs((x100-x101)./x100)

2.349138102570129e-7

In [25]:
sortperm(x100,rev=true), sort(x100,rev=true)

([89073,226411,241454,262860,134832,234704,136821,68889,105607,69358  …  281647,281700,281715,281728,281778,281785,281813,281849,281865,281888],[0.0113029,0.00926783,0.00829727,0.00302312,0.00300128,0.00257173,0.00245371,0.00243079,0.00239105,0.00236401  …  5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7])

## Doba preporuka 

NetFlix, Amazon Prime, PickBox, ... - on-line videoteke (filmovi i serije)

[NetFlix](https://www.netflix.com/hr/)

 * [80 milijuna korisnika](https://www.statista.com/statistics/250934/quarterly-number-of-netflix-streaming-subscribers-worldwide/), 5.000 filmova
 * [NetFlix Prize](http://www.kdd.org/kdd2014/tutorials/KDD%20-%20The%20Recommender%20Problem%20Revisited.pdf)
 

## Matematika

Netflix Recommendation Engine se temelji na aproksimaciji (velike i rijetke) matrice
```
M = Korisnici x Filmovi 
```
pomoću rastava singularnih vrijednosti (SVD): 

* [IncrementalSVD.jl](https://github.com/aaw/IncrementalSVD.jl)
* [A parallel recommendation engine in Julia](http://juliacomputing.com/blog/2016/04/22/a-parallel-recommendation-engine-in-julia.html)

## Pretraživanje

Redak $M[k,:]$ - što korisnik $k$ misli o filmovima

$$
\begin{bmatrix} \cdots & 1 & \cdots\end{bmatrix} \cdot  M
$$

Stupac $M[:,f]$ - što o filmu $f$ misle korisnici.

$$
M \cdot \begin{bmatrix} \vdots \\ 1 \\ \vdots\end{bmatrix}
$$

## Sličnost

Sličnost korisnika $i$ i $k$:

$$
\cos \angle (i,k)=\frac{(M[i,:],M[k,:])}{\|M[i,:]\| \cdot \|M[k,:]\|}
$$

Sličnost filmova $i$ i $k$:

$$
\cos \angle (i,k)=\frac{(M[:,i],M[:,k)}{\|M[:,i]\| \cdot \|M[:,k]\|}
$$

## Aproksimacija

Matrica $M$ je rijetka pa nemamo dovoljno informacija.

Kada se SVD rastav matrice $M=U\Sigma V^T$ aproksimira 

$$
M\approx U[:,1:m] \Sigma[1:m,1:m] V[:,1:m]^T
$$

za jako mali $m$ (npr. $m=25$), približna matrica je puna i daje dovoljno informacija.

Kako efikasno napraviti aproksimaciju? -> $\$$ 1.000.000  

In [60]:
# Pkg.clone("git://github.com/aaw/IncrementalSVD.jl.git")

In [2]:
import IncrementalSVD

INFO: Precompiling module ProgressMeter.

Use "Dict(a=>b for (a,b) in c)" instead.


In [9]:
rating_set = IncrementalSVD.load_small_movielens_dataset();

Reusing existing downloaded files...
Loading ratings 100% Time: 0:00:03


In [7]:
fieldnames(rating_set)

4-element Array{Symbol,1}:
 :training_set 
 :test_set     
 :user_to_index
 :item_to_index

In [61]:
# Format je (korisnik, film, ocjena)
rating_set.training_set

900188-element Array{IncrementalSVD.Rating,1}:
 IncrementalSVD.Rating(5006,2041,5.0)
 IncrementalSVD.Rating(3081,424,5.0) 
 IncrementalSVD.Rating(2414,274,4.0) 
 IncrementalSVD.Rating(3309,677,4.0) 
 IncrementalSVD.Rating(1147,3403,4.0)
 IncrementalSVD.Rating(5831,2307,4.0)
 IncrementalSVD.Rating(1266,2268,4.0)
 IncrementalSVD.Rating(1806,59,5.0)  
 IncrementalSVD.Rating(4742,211,4.0) 
 IncrementalSVD.Rating(5556,536,4.0) 
 IncrementalSVD.Rating(5082,1507,3.0)
 IncrementalSVD.Rating(777,557,1.0)  
 IncrementalSVD.Rating(3285,919,3.0) 
 ⋮                                   
 IncrementalSVD.Rating(93,206,3.0)   
 IncrementalSVD.Rating(3900,1749,3.0)
 IncrementalSVD.Rating(1524,1146,4.0)
 IncrementalSVD.Rating(4140,24,5.0)  
 IncrementalSVD.Rating(3479,492,4.0) 
 IncrementalSVD.Rating(3978,124,4.0) 
 IncrementalSVD.Rating(5565,612,4.0) 
 IncrementalSVD.Rating(1112,585,2.0) 
 IncrementalSVD.Rating(1224,1833,4.0)
 IncrementalSVD.Rating(1114,734,1.0) 
 IncrementalSVD.Rating(4577,1583,4.0)
 In

In [62]:
rating_set.test_set

100021-element Array{IncrementalSVD.Rating,1}:
 IncrementalSVD.Rating(6036,503,3.0) 
 IncrementalSVD.Rating(4279,615,3.0) 
 IncrementalSVD.Rating(4140,28,4.0)  
 IncrementalSVD.Rating(4663,2012,4.0)
 IncrementalSVD.Rating(1837,172,4.0) 
 IncrementalSVD.Rating(3841,2228,5.0)
 IncrementalSVD.Rating(508,1260,3.0) 
 IncrementalSVD.Rating(1545,133,3.0) 
 IncrementalSVD.Rating(3018,770,4.0) 
 IncrementalSVD.Rating(3018,24,4.0)  
 IncrementalSVD.Rating(3513,923,4.0) 
 IncrementalSVD.Rating(4957,767,4.0) 
 IncrementalSVD.Rating(660,386,3.0)  
 ⋮                                   
 IncrementalSVD.Rating(1899,1569,3.0)
 IncrementalSVD.Rating(3635,611,4.0) 
 IncrementalSVD.Rating(4474,1,5.0)   
 IncrementalSVD.Rating(5321,1529,4.0)
 IncrementalSVD.Rating(1755,532,4.0) 
 IncrementalSVD.Rating(2537,1273,4.0)
 IncrementalSVD.Rating(1789,953,2.0) 
 IncrementalSVD.Rating(1350,1008,3.0)
 IncrementalSVD.Rating(4933,102,5.0) 
 IncrementalSVD.Rating(1950,2502,3.0)
 IncrementalSVD.Rating(4888,408,3.0) 
 In

In [63]:
rating_set.user_to_index

Dict{AbstractString,Int32} with 6040 entries:
  "4304" => 4304
  "3935" => 3935
  "5422" => 5422
  "5734" => 5734
  "2243" => 2243
  "1881" => 1881
  "5425" => 5425
  "4209" => 4209
  "1907" => 1907
  "2923" => 2923
  "599"  => 599
  "2491" => 2491
  "5944" => 5944
  "228"  => 228
  "2590" => 2590
  "3697" => 3697
  "5031" => 5031
  "2579" => 2579
  "5551" => 5551
  "1880" => 1880
  "2562" => 2562
  "3215" => 3215
  "3991" => 3991
  "4652" => 4652
  "4088" => 4088
  ⋮      => ⋮

In [42]:
rating_set.item_to_index

Dict{AbstractString,Int32} with 3706 entries:
  "Fried Green Tomatoes (1991)"                                       => 594
  "Milk Money (1994)"                                                 => 1361
  "From Russia with Love (1963)"                                      => 729
  "House II: The Second Story (1987)"                                 => 1247
  "Held Up (2000)"                                                    => 3549
  "Missing in Action 2: The Beginning (1985)"                         => 2177
  "Murder, My Sweet (1944)"                                           => 996
  "Hidden, The (1987)"                                                => 981
  "Cable Guy, The (1996)"                                             => 669
  "Big Kahuna, The (2000)"                                            => 893
  "Addams Family Values (1993)"                                       => 1857
  "Farinelli: il castrato (1994)"                                     => 1945
  "Education of Little T

In [84]:
keys(rating_set.item_to_index)

Base.KeyIterator for a Dict{AbstractString,Int32} with 3706 entries. Keys:
  "Fried Green Tomatoes (1991)"
  "Milk Money (1994)"
  "From Russia with Love (1963)"
  "House II: The Second Story (1987)"
  "Held Up (2000)"
  "Missing in Action 2: The Beginning (1985)"
  "Murder, My Sweet (1944)"
  "Hidden, The (1987)"
  "Cable Guy, The (1996)"
  "Big Kahuna, The (2000)"
  "Addams Family Values (1993)"
  "Farinelli: il castrato (1994)"
  "Education of Little Tree, The (1997)"
  "In God's Hands (1998)"
  "Last Man Standing (1996)"
  "Sixth Sense, The (1999)"
  "Star Maps (1997)"
  "Girl, Interrupted (1999)"
  "Stand by Me (1986)"
  "Rob Roy (1995)"
  "Caligula (1980)"
  "Flirting With Disaster (1996)"
  "Hook (1991)"
  "Institute Benjamenta, or This Dream People Call Human Life (1995)"
  ⋮

In [47]:
values(rating_set.item_to_index)

Base.ValueIterator for a Dict{AbstractString,Int32} with 3706 entries. Values:
  594
  1361
  729
  1247
  3549
  2177
  996
  981
  669
  893
  1857
  1945
  2759
  2814
  1840
  39
  2670
  32
  85
  449
  2532
  1290
  657
  3397
  ⋮

In [101]:
rating_set.item_to_index["Fried Green Tomatoes (1991)"]

594

In [102]:
# Nađimo "Blade runner"
for k in keys(rating_set.item_to_index)
    if contains(k,"Blade")
        println(k)
    end
end

Sling Blade (1996)
Blade (1998)
Blade Runner (1982)
Some Folks Call It a Sling Blade (1993)


LoadError: LoadError: UnicodeError: invalid character index
while loading In[102], in expression starting on line 2

In [103]:
get(rating_set.item_to_index,"Blade Runner (1982)",0)

744

In [5]:
# Ovo traje dvije minute
model = IncrementalSVD.train(rating_set, 25);

Computing truncated rank 25 SVD 100% Time: 0:02:16


In [15]:
fieldnames(model)

5-element Array{Symbol,1}:
 :user_to_index
 :item_to_index
 :U            
 :S            
 :V            

In [17]:
model.U

6040×25 Array{Float32,2}:
 0.0109397   0.0120882    0.0169468    …   0.0182744    0.0127905  
 0.0139128   0.0105115    0.0109548        0.00726907   0.0115994  
 0.0103488   0.00919027   0.0170757        0.00782491   0.0189602  
 0.00643328  0.00658507   0.0150251        0.00898337   0.0145874  
 0.0135069   0.0159129    0.00188229      -0.0017402    0.0134213  
 0.0108626   0.0169864    0.014689     …   0.0109867    0.01205    
 0.00905656  0.00757497   0.0188016        0.00902981   0.0157905  
 0.015726    0.0147907    0.010143         0.0130196    0.00672511 
 0.0136295   0.0087258    0.0111347        0.0135053    0.00672864 
 0.0189491   0.0126614   -0.00966637       0.0124152   -2.84942f-5 
 0.0131507   0.0106846    0.00996407   …   0.00812149   0.00857651 
 0.00579884  0.00825437   0.0137625        0.0119663    0.0201331  
 0.0125511   0.00975366   0.013059         0.00873861   0.0125369  
 ⋮                                     ⋱                           
 0.00629751  0.0126694

In [19]:
model.S

25-element Array{Float32,1}:
 8193.03  
 2141.83  
  822.532 
 1152.78  
  857.213 
 1207.82  
  635.458 
  386.565 
  356.42  
  257.805 
  253.264 
  335.431 
  294.861 
  220.93  
  255.133 
  290.461 
  305.247 
  212.039 
  206.682 
  183.221 
  185.071 
  165.08  
  137.357 
  117.028 
   98.6447

In [20]:
model.V

3706×25 Array{Float32,2}:
 0.0358245   0.00782668  0.0675527   …  -0.0100661    0.0137027 
 0.0247092   0.0150956   0.0188127      -0.00511937   0.00914619
 0.0303699   0.0131325   0.0314674      -0.00250202   0.00869294
 0.0317046   0.0121117   0.0539777       0.00839023  -0.00308282
 0.031558    0.00782683  0.0546983       0.00663257  -0.00126217
 0.0343401   0.00475581  0.0693303   …  -0.0231122    0.00700887
 0.0303488   0.00794795  0.0289065       0.00364954   0.00895373
 0.033034    0.00395536  0.052396        0.0155467    0.00311064
 0.0287153   0.00829325  0.0232587       0.0023214    0.0277448 
 0.0333828   0.00531967  0.0538163      -0.0148109    0.0360311 
 0.0301238   0.00558839  0.0378453   …   0.0106465   -0.014266  
 0.0170121   0.027131    0.0101034       0.0135378    0.00748064
 0.0257305   0.018903    0.0120745       0.00819141   0.00644709
 ⋮                                   ⋱                          
 0.00118642  0.00260609  0.00407268      0.014045     0.0141222 

In [35]:
IncrementalSVD.items(model)

Base.KeyIterator for a Dict{AbstractString,Int32} with 3706 entries. Keys:
  "Fried Green Tomatoes (1991)"
  "Milk Money (1994)"
  "From Russia with Love (1963)"
  "House II: The Second Story (1987)"
  "Held Up (2000)"
  "Missing in Action 2: The Beginning (1985)"
  "Murder, My Sweet (1944)"
  "Hidden, The (1987)"
  "Cable Guy, The (1996)"
  "Big Kahuna, The (2000)"
  "Addams Family Values (1993)"
  "Farinelli: il castrato (1994)"
  "Education of Little Tree, The (1997)"
  "In God's Hands (1998)"
  "Last Man Standing (1996)"
  "Sixth Sense, The (1999)"
  "Star Maps (1997)"
  "Girl, Interrupted (1999)"
  "Stand by Me (1986)"
  "Rob Roy (1995)"
  "Caligula (1980)"
  "Flirting With Disaster (1996)"
  "Hook (1991)"
  "Institute Benjamenta, or This Dream People Call Human Life (1995)"
  ⋮

In [39]:
IncrementalSVD.similar_items(model, "Friday the 13th (1980)")

10-element Array{SubString{String},1}:
 "Friday the 13th (1980)"                               
 "Amityville Horror, The (1979)"                        
 "Jaws 2 (1978)"                                        
 "Cujo (1983)"                                          
 "Friday the 13th Part 2 (1981)"                        
 "Porky's (1981)"                                       
 "Pet Sematary (1989)"                                  
 "Omen, The (1976)"                                     
 "Soylent Green (1973)"                                 
 "Nightmare on Elm Street 4: The Dream Master, A (1988)"

In [24]:
@which IncrementalSVD.similar_items(model, "Friday the 13th (1980)")

similar_items(model::IncrementalSVD.RatingsModel, item) at /home/slap/.julia/v0.5/IncrementalSVD/src/util.jl:113

In [25]:
IncrementalSVD.similar_items(model, "Godfather, The (1972)")

10-element Array{SubString{String},1}:
 "Godfather, The (1972)"                    
 "Godfather: Part II, The (1974)"           
 "GoodFellas (1990)"                        
 "One Flew Over the Cuckoo's Nest (1975)"   
 "Taxi Driver (1976)"                       
 "Butch Cassidy and the Sundance Kid (1969)"
 "Silence of the Lambs, The (1991)"         
 "Graduate, The (1967)"                     
 "Apocalypse Now (1979)"                    
 "Casablanca (1942)"                        

In [ ]:
# The 1st feature is the pricipal vector, similar to Principal Component Analysis. 
IncrementalSVD.show_items_by_feature(model, 1)

In [ ]:
IncrementalSVD.show_items_by_feature(model, 2)

In [ ]:
IncrementalSVD.item_features(model, "Nueba Yol (1995)")

In [27]:
IncrementalSVD.user_ratings(rating_set, "3000")

97-element Array{Tuple{SubString{String},Float32},1}:
 ("Brothers McMullen, The (1995)",5.0)                
 ("Rock, The (1996)",5.0)                             
 ("Caddyshack (1980)",5.0)                            
 ("Twelve Monkeys (1995)",5.0)                        
 ("Groundhog Day (1993)",5.0)                         
 ("Time Bandits (1981)",5.0)                          
 ("Princess Bride, The (1987)",5.0)                   
 ("Babe (1995)",5.0)                                  
 ("Gattaca (1997)",5.0)                               
 ("Dances with Wolves (1990)",5.0)                    
 ("American Beauty (1999)",5.0)                       
 ("One Flew Over the Cuckoo's Nest (1975)",5.0)       
 ("Defending Your Life (1991)",5.0)                   
 ⋮                                                    
 ("Mad Max (1979)",2.0)                               
 ("Forrest Gump (1994)",2.0)                          
 ("Blue Lagoon, The (1980)",1.0)                      
 ("Mission:

In [28]:
IncrementalSVD.get_predicted_rating(model, "3000", "Blade Runner (1982)")

4.3903804f0

In [29]:
IncrementalSVD.get_predicted_rating(model, "3000", "Footloose (1984)")

2.8983767f0

## Tehnologija - github

Open Source!

[github]() je sustav za kolaborativan razvoj softvera - izlog!


## Julia i Jupyter

[Julia](http://julialang.org/) je novi programski jezik (evolucija) za BigData

* [JuliaBox](https://juliabox.com/)

[Jupyter](http://jupyter.org/) bilježnice:
 
 * pisanje teksta i izvođenje programa na 40 jezika (Julia, Python, R, ...)
 * pretvaranje u HTML i knjigu (LaTeX, PDF)
 * prezentacija, sastavljanje domaćih radova

## Hvala na pažnji

Pitanja?