# Novo doba

_Predavanje na otvorenju Centra izvrsnosti iz matematike Splitsko-dalmatinske županije_

Ivan Slapničar, Sveučilište u Splitu, FESB



## Poruke

Lako - Teško (u svemu!)

Sada - doba __pretraživanja__ -> _matematika_

Dolazi - doba __preporuka__  -> _matematika_

(BigData)


## Lako - teško

vaganje:  1 _kg_  -> 1 _kg_ $\pm$ 0.000000001 _kg_

trčanje: 100 _m_ -> 42,195 _m_ ili 100 _m_ < 10 _sek_

zadaci iz matematike: test za CI -> državno natjecanje ([2016](http://natjecanja.math.hr/drzavno-natjecanje/drzavno-2016/) ili [sve](http://www.antonija-horvatek.from.hr/natjecanja-iz-matematike/zadaci-SS.htm)), ili [matematička olimpijada](http://www.imo-official.org/)

## Doba pretraživanja

google (i ostali)


* [50 milijardi stranica](http://www.worldwidewebsize.com/), [3.5 milijarde pretraživanja dnevno](http://www.internetlivestats.com/google-search-statistics/)
* __PageRank__
* povijest, kontekst - cookies, spremanje podataka (o vama), [200+ parametara](http://backlinko.com/google-ranking-factors)

## PageRank

* Teorija grafova i linearna algebra
* [C, Moler, Google PageRank][Mol11]


[Mol11]: https://www.mathworks.com/moler/exm/chapters/pagerank.pdf "C, Moler, 'Google PageRank', mathWorks, 2011."


In [26]:
i = vec([ 2 6 3 4 4 5 6 1 1])
j = vec([ 1 1 2 2 3 3 3 4 6])
G=sparse(i,j,1.0)

6×6 sparse matrix with 9 Float64 nonzero entries:
	[2, 1]  =  1.0
	[6, 1]  =  1.0
	[3, 2]  =  1.0
	[4, 2]  =  1.0
	[4, 3]  =  1.0
	[5, 3]  =  1.0
	[6, 3]  =  1.0
	[1, 4]  =  1.0
	[1, 6]  =  1.0

In [27]:
full(G)

6×6 Array{Float64,2}:
 0.0  0.0  0.0  1.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0

Na graf primijenimo slučajnu šetnju (_random walk_)- vjerojatnost da pratimo bilo koji link je jednaka:

In [28]:
c=sum(G,1)
n=size(G,1)
for j=1:n
    if c[j]>0
        G[:,j]=G[:,j]/c[j]
    end
end
full(G)

6×6 Array{Float64,2}:
 0.0  0.0  0.0       1.0  0.0  1.0
 0.5  0.0  0.0       0.0  0.0  0.0
 0.0  0.5  0.0       0.0  0.0  0.0
 0.0  0.5  0.333333  0.0  0.0  0.0
 0.0  0.0  0.333333  0.0  0.0  0.0
 0.5  0.0  0.333333  0.0  0.0  0.0

* $p$: vjerojatnost da pratimo neki link
* $1-p$:  je vjerojatnost da odemo na neku drugu slučajnu stranicu
* google koristi $p=0.85$ ?

In [29]:
p=0.85
z = ((1-p)*(c.!=0) + (c.==0))/n
A=p*G+ones(n)*z

6×6 Array{Float64,2}:
 0.025  0.025  0.025     0.875  0.166667  0.875
 0.45   0.025  0.025     0.025  0.166667  0.025
 0.025  0.45   0.025     0.025  0.166667  0.025
 0.025  0.45   0.308333  0.025  0.166667  0.025
 0.025  0.025  0.308333  0.025  0.166667  0.025
 0.45   0.025  0.308333  0.025  0.166667  0.025

Pokrenimo slučajnu šetnju od vektora $x_0=\begin{bmatrix} 1/n \\ 1/n \\ \vdots \\ 1/n \end{bmatrix}$.

Sljedeći vektori u nizu su 

$$
x_1=A\cdot x_0 \\
x_2=A\cdot x_1 \\
x_3=A\cdot x_2\\
\vdots
$$

Kada se algoritam stabilizira, odnosno kada je 

$$
A\cdot x\approx x,
$$

tada je element vektora $x[i]$ __rang stranice__ $i$.

In [13]:
function myPageRank(G::SparseMatrixCSC{Float64,Int64},steps::Int)
    p=0.85
    c=sum(G,1)/p
    n=size(G,1)
    for i=1:n
        G.nzval[G.colptr[i]:G.colptr[i+1]-1]./=c[i]
    end
    e=ones(n)
    x=e/n
    z = vec(((1-p)*(c.!=0) + (c.==0))/n)
    for j=1:steps
        x=G*x+(z⋅x)
    end
    x/norm(x,1)
end

myPageRank (generic function with 1 method)

In [15]:
myPageRank(G,15)

6-element Array{Float64,1}:
 0.321024 
 0.170538 
 0.106596 
 0.136795 
 0.0643103
 0.200737 

### [Stanford web graph](http://snap.stanford.edu/data/web-Stanford.html)

Malo veći testni problem.

In [18]:
W=readdlm("web-Stanford.txt",Int)

2312497×2 Array{Int64,2}:
      1    6548
      1   15409
   6548   57031
  15409   13102
      2   17794
      2   25202
      2   53625
      2   54582
      2   64930
      2   73764
      2   84477
      2   98628
      2  100193
      ⋮        
 281849  165189
 281849  177014
 281849  226290
 281849  243180
 281849  244195
 281849  247252
 281849  281568
 281865  186750
 281865  225872
 281888  114388
 281888  192969
 281888  233184

In [19]:
S=sparse(W[:,2],W[:,1],1.0)

281903×281903 sparse matrix with 2312497 Float64 nonzero entries:
	[6548  ,      1]  =  1.0
	[15409 ,      1]  =  1.0
	[17794 ,      2]  =  1.0
	[25202 ,      2]  =  1.0
	[53625 ,      2]  =  1.0
	[54582 ,      2]  =  1.0
	[64930 ,      2]  =  1.0
	[73764 ,      2]  =  1.0
	[84477 ,      2]  =  1.0
	[98628 ,      2]  =  1.0
	⋮
	[168703, 281902]  =  1.0
	[180771, 281902]  =  1.0
	[266504, 281902]  =  1.0
	[275189, 281902]  =  1.0
	[44103 , 281903]  =  1.0
	[56088 , 281903]  =  1.0
	[90591 , 281903]  =  1.0
	[94440 , 281903]  =  1.0
	[216688, 281903]  =  1.0
	[256539, 281903]  =  1.0
	[260899, 281903]  =  1.0

In [20]:
@time x100=myPageRank(S,100);

  1.491916 seconds (846.80 k allocations: 542.598 MB, 11.86% gc time)


In [21]:
x101=myPageRank(S,101)
maxabs((x100-x101)./x100)

2.349138102570129e-7

In [25]:
sortperm(x100,rev=true), sort(x100,rev=true)

([89073,226411,241454,262860,134832,234704,136821,68889,105607,69358  …  281647,281700,281715,281728,281778,281785,281813,281849,281865,281888],[0.0113029,0.00926783,0.00829727,0.00302312,0.00300128,0.00257173,0.00245371,0.00243079,0.00239105,0.00236401  …  5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7])

## Doba preporuka 

NetFlix, Amazon Prime, PickBox, ... - on-line videoteke (filmovi i serije)

[NetFlix](https://www.netflix.com/hr/)

 * [80 milijuna korisnika](https://www.statista.com/statistics/250934/quarterly-number-of-netflix-streaming-subscribers-worldwide/)
 * 5.000 filmova

## Assignment 1$^*$

The Netflix Recommendation Engine is based on the principle of a low-rank (truncated) SVD approximation of the 
(large and sparse) Movie $\times$ Users matrix, and the SVD updating. 

Explain the mathematics behind the engine
using explanations from the packages [IncrementalSVD.jl](https://github.com/aaw/IncrementalSVD.jl),
and [RecSys.jl](https://github.com/abhijithch/RecSys.jl/) (see also 
[A parallel recommendation engine in Julia](http://juliacomputing.com/blog/2016/04/22/a-parallel-recommendation-engine-in-julia.html)), and the literature on the Internet.

Explain the relation to SVD, truncated SVD, and SVD updating.

Try the packages.

In [ ]:
# Pkg.clone("git://github.com/aaw/IncrementalSVD.jl.git")
import IncrementalSVD

In [ ]:
whos(IncrementalSVD)

In [ ]:
rating_set = IncrementalSVD.load_small_movielens_dataset();

In [ ]:
# This takes several minutes
model = IncrementalSVD.train(rating_set, 25);

In [ ]:
IncrementalSVD.items(model)

In [ ]:
rating_set.item_to_index


In [ ]:
rating_set.user_to_index

In [ ]:
IncrementalSVD.similar_items(model, "Friday the 13th (1980)")

In [ ]:
IncrementalSVD.similar_items(model, "Godfather, The (1972)")

In [ ]:
# The 1st feature is the pricipal vector, similar to Principal Component Analysis. 
IncrementalSVD.show_items_by_feature(model, 1)

In [ ]:
IncrementalSVD.show_items_by_feature(model, 2)

In [ ]:
IncrementalSVD.item_features(model, "Nueba Yol (1995)")

In [ ]:
IncrementalSVD.user_ratings(rating_set, "3000")

In [ ]:
IncrementalSVD.get_predicted_rating(model, "3000", "Blade Runner (1982)")

In [ ]:
IncrementalSVD.get_predicted_rating(model, "3000", "Footloose (1984)")