# Novo doba

_Predavanje na otvorenju Centra izvrsnosti iz matematike Splitsko-dalmatinske županije_


Ivan Slapničar, Sveučilište u Splitu, FESB



## Poruke

Lako - Teško (u svemu!)

Sada - doba __pretraživanja__ -> _matematika_

Dolazi - doba __preporuka__  -> _matematika_

(BigData, nova tehnologija)


## Lako - teško

vaganje:  1 _kg_  -> 1 _kg_ $\pm$ 0.000000001 _kg_

trčanje: 100 _m_ -> 42,195 _m_ ili 100 _m_ < 10 _sek_

zadaci iz matematike: test za CI -> državno natjecanje ([2016](http://natjecanja.math.hr/drzavno-natjecanje/drzavno-2016/) ili [sve](http://www.antonija-horvatek.from.hr/natjecanja-iz-matematike/zadaci-SS.htm)), ili [matematička olimpijada](http://www.imo-official.org/)

## Doba pretraživanja

google (i ostali)


* [50 milijardi stranica](http://www.worldwidewebsize.com/), [3.5 milijarde pretraživanja dnevno](http://www.internetlivestats.com/google-search-statistics/)
* __PageRank__
* povijest, kontekst - cookies, spremanje podataka (o vama), [200+ parametara](http://backlinko.com/google-ranking-factors)

## PageRank

* Teorija grafova i linearna algebra
* [C, Moler, Google PageRank][Mol11]


[Mol11]: https://www.mathworks.com/moler/exm/chapters/pagerank.pdf "C, Moler, 'Google PageRank', mathWorks, 2011."


In [1]:
i = vec([ 2 6 3 4 4 5 6 1 1])
j = vec([ 1 1 2 2 3 3 3 4 6])
G=sparse(i,j,1.0)

6×6 sparse matrix with 9 Float64 nonzero entries:
	[2, 1]  =  1.0
	[6, 1]  =  1.0
	[3, 2]  =  1.0
	[4, 2]  =  1.0
	[4, 3]  =  1.0
	[5, 3]  =  1.0
	[6, 3]  =  1.0
	[1, 4]  =  1.0
	[1, 6]  =  1.0

In [2]:
full(G)

6×6 Array{Float64,2}:
 0.0  0.0  0.0  1.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  1.0  1.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 1.0  0.0  1.0  0.0  0.0  0.0

Na graf primijenimo slučajnu šetnju (_random walk_)- vjerojatnost da pratimo bilo koji link je jednaka:

In [3]:
c=sum(G,1)
n=size(G,1)
for j=1:n
    if c[j]>0
        G[:,j]=G[:,j]/c[j]
    end
end
full(G)

6×6 Array{Float64,2}:
 0.0  0.0  0.0       1.0  0.0  1.0
 0.5  0.0  0.0       0.0  0.0  0.0
 0.0  0.5  0.0       0.0  0.0  0.0
 0.0  0.5  0.333333  0.0  0.0  0.0
 0.0  0.0  0.333333  0.0  0.0  0.0
 0.5  0.0  0.333333  0.0  0.0  0.0

* $p$: vjerojatnost da pratimo neki link
* $1-p$:  je vjerojatnost da odemo na neku drugu slučajnu stranicu
* google koristi $p=0.85$ ?

In [4]:
p=0.85
z = ((1-p)*(c.!=0) + (c.==0))/n
A=p*G+ones(n)*z

6×6 Array{Float64,2}:
 0.025  0.025  0.025     0.875  0.166667  0.875
 0.45   0.025  0.025     0.025  0.166667  0.025
 0.025  0.45   0.025     0.025  0.166667  0.025
 0.025  0.45   0.308333  0.025  0.166667  0.025
 0.025  0.025  0.308333  0.025  0.166667  0.025
 0.45   0.025  0.308333  0.025  0.166667  0.025

Krenimo u slučajnu šetnju od vektora $x_0=\begin{bmatrix} 1/n \\ 1/n \\ \vdots \\ 1/n \end{bmatrix}$.

Sljedeći vektori u nizu su 

$$
x_1=A\cdot x_0 \\
x_2=A\cdot x_1 \\
x_3=A\cdot x_2\\
\vdots
$$

Kada se algoritam stabilizira, odnosno kada je 

$$
A\cdot x\approx x,
$$

tada je element vektora $x[i]$ __rang stranice__ $i$.

In [5]:
function myPageRank(G::SparseMatrixCSC{Float64,Int64},steps::Int)
    p=0.85
    c=sum(G,1)/p
    n=size(G,1)
    for i=1:n
        G.nzval[G.colptr[i]:G.colptr[i+1]-1]./=c[i]
    end
    e=ones(n)
    x=e/n
    z = vec(((1-p)*(c.!=0) + (c.==0))/n)
    for j=1:steps
        x=G*x+(z⋅x)
    end
    x/norm(x,1)
end

myPageRank (generic function with 1 method)

In [6]:
myPageRank(G,15)

6-element Array{Float64,1}:
 0.321024 
 0.170538 
 0.106596 
 0.136795 
 0.0643103
 0.200737 

### [Stanford web graph](http://snap.stanford.edu/data/web-Stanford.html)

Malo veći testni problem.

In [7]:
W=readdlm("web-Stanford.txt",Int)

2312497×2 Array{Int64,2}:
      1    6548
      1   15409
   6548   57031
  15409   13102
      2   17794
      2   25202
      2   53625
      2   54582
      2   64930
      2   73764
      2   84477
      2   98628
      2  100193
      ⋮        
 281849  165189
 281849  177014
 281849  226290
 281849  243180
 281849  244195
 281849  247252
 281849  281568
 281865  186750
 281865  225872
 281888  114388
 281888  192969
 281888  233184

In [8]:
S=sparse(W[:,2],W[:,1],1.0)

281903×281903 sparse matrix with 2312497 Float64 nonzero entries:
	[6548  ,      1]  =  1.0
	[15409 ,      1]  =  1.0
	[17794 ,      2]  =  1.0
	[25202 ,      2]  =  1.0
	[53625 ,      2]  =  1.0
	[54582 ,      2]  =  1.0
	[64930 ,      2]  =  1.0
	[73764 ,      2]  =  1.0
	[84477 ,      2]  =  1.0
	[98628 ,      2]  =  1.0
	⋮
	[168703, 281902]  =  1.0
	[180771, 281902]  =  1.0
	[266504, 281902]  =  1.0
	[275189, 281902]  =  1.0
	[44103 , 281903]  =  1.0
	[56088 , 281903]  =  1.0
	[90591 , 281903]  =  1.0
	[94440 , 281903]  =  1.0
	[216688, 281903]  =  1.0
	[256539, 281903]  =  1.0
	[260899, 281903]  =  1.0

In [9]:
@time x100=myPageRank(S,100);

  1.813601 seconds (846.80 k allocations: 542.598 MB, 13.46% gc time)


In [10]:
x101=myPageRank(S,101)
maxabs((x100-x101)./x100)

2.349138102570129e-7

In [11]:
sortperm(x100,rev=true), sort(x100,rev=true)

([89073,226411,241454,262860,134832,234704,136821,68889,105607,69358  …  281647,281700,281715,281728,281778,281785,281813,281849,281865,281888],[0.0113029,0.00926783,0.00829727,0.00302312,0.00300128,0.00257173,0.00245371,0.00243079,0.00239105,0.00236401  …  5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7,5.33369e-7])

## Doba preporuka 

NetFlix, Amazon Prime, PickBox, ... - on-line videoteke (filmovi i serije)

[NetFlix](https://www.netflix.com/hr/)

 * [80 milijuna korisnika](https://www.statista.com/statistics/250934/quarterly-number-of-netflix-streaming-subscribers-worldwide/), 5.000 filmova
 * [NetFlix Prize](http://www.kdd.org/kdd2014/tutorials/KDD%20-%20The%20Recommender%20Problem%20Revisited.pdf)
 

## Matematika

Netflix Recommendation Engine se temelji na aproksimaciji (velike i rijetke) matrice
```
M = Korisnici x Filmovi 
```
pomoću rastava singularnih vrijednosti (SVD): 

* [IncrementalSVD.jl](https://github.com/aaw/IncrementalSVD.jl)
* [A parallel recommendation engine in Julia](http://juliacomputing.com/blog/2016/04/22/a-parallel-recommendation-engine-in-julia.html)

## Sličnost

Sličnost korisnika $i$ i $k$:
$$
\cos \angle (i,k)=\frac{(M[i,:],M[k,:])}{\|M[i,:]\| \cdot \|M[k,:]\|}
$$
Sličnost filmova $i$ i $k$:
$$
\cos \angle (i,k)=\frac{(M[:,i],M[:,k)}{\|M[:,i]\| \cdot \|M[:,k]\|}
$$

## Pretraživanje

Redak $M[k,:]$ - što korisnik $k$ misli o filmovima.

Stupac $M[:,f]$ - što o filmu $f$ misle korisnici

Element $M[k,f]$ - što korisnik $k$ misli o filmu $f$.

## Problem

Matrica $M$ je rijetka pa nemamo dovoljno informacija. Na primjer, 

```
900188 ocjena / ( 6040 korisnika x 3706 filmova ) = 4%
```

## Aproksimacija

SVD rastav $M=U\Sigma V^T$ se aproksimira matricom jako malog ranga (npr. $m=25$)

![SVD rastav](svd.png)

Približna matrica je puna i daje dovoljno informacija.

Efikasna aproksimacija? -> $\$$ 1.000.000  

In [12]:
# Pkg.clone("git://github.com/aaw/IncrementalSVD.jl.git")

In [13]:
using IncrementalSVD

In [14]:
whos(IncrementalSVD)

                IncrementalSVD     56 KB     Module
                        Rating    136 bytes  DataType
                     RatingSet    148 bytes  DataType
                  RatingsModel    160 bytes  DataType
             cosine_similarity      0 bytes  IncrementalSVD.#cosine_similarity
          get_predicted_rating      0 bytes  IncrementalSVD.#get_predicted_rati…
                 item_features      0 bytes  IncrementalSVD.#item_features
                   item_search      0 bytes  IncrementalSVD.#item_search
                         items      0 bytes  IncrementalSVD.#items
    load_book_crossing_dataset      0 bytes  IncrementalSVD.#load_book_crossing…
  load_large_movielens_dataset      0 bytes  IncrementalSVD.#load_large_moviele…
  load_small_movielens_dataset      0 bytes  IncrementalSVD.#load_small_moviele…
                          rmse      0 bytes  IncrementalSVD.#rmse
                 similar_items      0 bytes  IncrementalSVD.#similar_items
                 similar_us

In [15]:
rating_set = load_small_movielens_dataset();

Reusing existing downloaded files...
Loading ratings 100% Time: 0:00:04


In [16]:
fieldnames(rating_set)

4-element Array{Symbol,1}:
 :training_set 
 :test_set     
 :user_to_index
 :item_to_index

In [17]:
# Format je (korisnik, film, ocjena)
rating_set.training_set

900188-element Array{IncrementalSVD.Rating,1}:
 IncrementalSVD.Rating(5790,373,3.0) 
 IncrementalSVD.Rating(1587,801,3.0) 
 IncrementalSVD.Rating(4784,23,3.0)  
 IncrementalSVD.Rating(1912,1517,1.0)
 IncrementalSVD.Rating(3163,840,5.0) 
 IncrementalSVD.Rating(5434,1059,4.0)
 IncrementalSVD.Rating(1476,177,4.0) 
 IncrementalSVD.Rating(1274,1023,4.0)
 IncrementalSVD.Rating(3412,129,5.0) 
 IncrementalSVD.Rating(1128,2626,4.0)
 IncrementalSVD.Rating(2063,139,3.0) 
 IncrementalSVD.Rating(1425,1054,2.0)
 IncrementalSVD.Rating(996,1372,4.0) 
 ⋮                                   
 IncrementalSVD.Rating(1584,950,4.0) 
 IncrementalSVD.Rating(175,548,5.0)  
 IncrementalSVD.Rating(2067,1011,4.0)
 IncrementalSVD.Rating(4899,623,3.0) 
 IncrementalSVD.Rating(4508,2960,1.0)
 IncrementalSVD.Rating(5387,2531,3.0)
 IncrementalSVD.Rating(2880,885,4.0) 
 IncrementalSVD.Rating(2781,739,4.0) 
 IncrementalSVD.Rating(2907,42,3.0)  
 IncrementalSVD.Rating(4169,8,4.0)   
 IncrementalSVD.Rating(2974,476,4.0) 
 In

In [18]:
rating_set.test_set

100021-element Array{IncrementalSVD.Rating,1}:
 IncrementalSVD.Rating(3808,90,2.0)  
 IncrementalSVD.Rating(2663,245,3.0) 
 IncrementalSVD.Rating(2164,851,3.0) 
 IncrementalSVD.Rating(660,548,3.0)  
 IncrementalSVD.Rating(5397,152,3.0) 
 IncrementalSVD.Rating(1941,886,3.0) 
 IncrementalSVD.Rating(4425,445,4.0) 
 IncrementalSVD.Rating(3017,106,4.0) 
 IncrementalSVD.Rating(1383,1065,5.0)
 IncrementalSVD.Rating(33,1588,4.0)  
 IncrementalSVD.Rating(4480,742,5.0) 
 IncrementalSVD.Rating(549,770,5.0)  
 IncrementalSVD.Rating(352,1658,4.0) 
 ⋮                                   
 IncrementalSVD.Rating(3539,427,5.0) 
 IncrementalSVD.Rating(608,1578,2.0) 
 IncrementalSVD.Rating(2080,1159,3.0)
 IncrementalSVD.Rating(5139,387,5.0) 
 IncrementalSVD.Rating(5446,560,5.0) 
 IncrementalSVD.Rating(393,2484,5.0) 
 IncrementalSVD.Rating(329,644,4.0)  
 IncrementalSVD.Rating(3729,1020,5.0)
 IncrementalSVD.Rating(901,417,3.0)  
 IncrementalSVD.Rating(4387,32,5.0)  
 IncrementalSVD.Rating(1317,3074,3.0)
 In

In [19]:
# Korisnici i njihove šifre
rating_set.user_to_index

Dict{AbstractString,Int32} with 6040 entries:
  "4304" => 4304
  "3935" => 3935
  "5422" => 5422
  "5734" => 5734
  "2243" => 2243
  "1881" => 1881
  "5425" => 5425
  "4209" => 4209
  "1907" => 1907
  "2923" => 2923
  "599"  => 599
  "2491" => 2491
  "5944" => 5944
  "228"  => 228
  "2590" => 2590
  "3697" => 3697
  "5031" => 5031
  "2579" => 2579
  "5551" => 5551
  "1880" => 1880
  "2562" => 2562
  "3215" => 3215
  "3991" => 3991
  "4652" => 4652
  "4088" => 4088
  ⋮      => ⋮

In [20]:
# Filmovi i njihove šifre
rating_set.item_to_index

Dict{AbstractString,Int32} with 3706 entries:
  "Fried Green Tomatoes (1991)"                                       => 594
  "Milk Money (1994)"                                                 => 1361
  "From Russia with Love (1963)"                                      => 729
  "House II: The Second Story (1987)"                                 => 1247
  "Held Up (2000)"                                                    => 3549
  "Missing in Action 2: The Beginning (1985)"                         => 2177
  "Murder, My Sweet (1944)"                                           => 996
  "Hidden, The (1987)"                                                => 981
  "Cable Guy, The (1996)"                                             => 669
  "Big Kahuna, The (2000)"                                            => 893
  "Addams Family Values (1993)"                                       => 1857
  "Farinelli: il castrato (1994)"                                     => 1945
  "Education of Little T

In [21]:
# Možemo posebno izvaditi naslove ...
keys(rating_set.item_to_index)

Base.KeyIterator for a Dict{AbstractString,Int32} with 3706 entries. Keys:
  "Fried Green Tomatoes (1991)"
  "Milk Money (1994)"
  "From Russia with Love (1963)"
  "House II: The Second Story (1987)"
  "Held Up (2000)"
  "Missing in Action 2: The Beginning (1985)"
  "Murder, My Sweet (1944)"
  "Hidden, The (1987)"
  "Cable Guy, The (1996)"
  "Big Kahuna, The (2000)"
  "Addams Family Values (1993)"
  "Farinelli: il castrato (1994)"
  "Education of Little Tree, The (1997)"
  "In God's Hands (1998)"
  "Last Man Standing (1996)"
  "Sixth Sense, The (1999)"
  "Star Maps (1997)"
  "Girl, Interrupted (1999)"
  "Stand by Me (1986)"
  "Rob Roy (1995)"
  "Caligula (1980)"
  "Flirting With Disaster (1996)"
  "Hook (1991)"
  "Institute Benjamenta, or This Dream People Call Human Life (1995)"
  ⋮

In [22]:
# i šifre
values(rating_set.item_to_index)

Base.ValueIterator for a Dict{AbstractString,Int32} with 3706 entries. Values:
  594
  1361
  729
  1247
  3549
  2177
  996
  981
  669
  893
  1857
  1945
  2759
  2814
  1840
  39
  2670
  32
  85
  449
  2532
  1290
  657
  3397
  ⋮

In [23]:
# Koje je filmove ocijenio korisnik "3000"
user_ratings(rating_set, "3000")

96-element Array{Tuple{SubString{String},Float32},1}:
 ("American Beauty (1999)",5.0)                       
 ("Groundhog Day (1993)",5.0)                         
 ("Defending Your Life (1991)",5.0)                   
 ("Dances with Wolves (1990)",5.0)                    
 ("Time Bandits (1981)",5.0)                          
 ("When Harry Met Sally... (1989)",5.0)               
 ("Gattaca (1997)",5.0)                               
 ("Rock, The (1996)",5.0)                             
 ("Babe (1995)",5.0)                                  
 ("Brothers McMullen, The (1995)",5.0)                
 ("Princess Bride, The (1987)",5.0)                   
 ("Brazil (1985)",5.0)                                
 ("One Flew Over the Cuckoo's Nest (1975)",5.0)       
 ⋮                                                    
 ("Young Sherlock Holmes (1985)",2.0)                 
 ("Back to the Future (1985)",2.0)                    
 ("Dark Crystal, The (1982)",2.0)                     
 ("2001: A 

In [24]:
# Nađimo točan naziv i šifru za "Blade runner"
for k in keys(rating_set.item_to_index)
    if contains(k,"Blade")
        println(k)
    end
end

Sling Blade (1996)
Blade (1998)
Blade Runner (1982)
Some Folks Call It a Sling Blade (1993)


LoadError: LoadError: UnicodeError: invalid character index
while loading In[24], in expression starting on line 2

In [25]:
get(rating_set.item_to_index,"Blade Runner (1982)",0)

744

In [26]:
# Da li je korisnik "3000" ocijenio "Blade Runner" ?
for k in user_ratings(rating_set,"3000")
    if contains(k[1],"Blade")
        println(k)
    end
end

In [27]:
# Da li je korisnik "3000" ocijenio "Citizen Kane" ?
for k in user_ratings(rating_set,"3000")
    if contains(k[1],"Citizen")
        println(k)
    end
end

In [28]:
# Ovo traje dvije i po minute
model = train(rating_set, 25);

Computing truncated rank 25 SVD 100% Time: 0:02:31


In [29]:
fieldnames(model)

5-element Array{Symbol,1}:
 :user_to_index
 :item_to_index
 :U            
 :S            
 :V            

In [30]:
model.U

6040×25 Array{Float32,2}:
 0.0101124   0.0116776    0.0168061   0.00919807  …   0.016471     0.0141891 
 0.0141477   0.011056     0.00970759  0.0109542       0.00851747   0.0129143 
 0.00994222  0.00888608   0.0162732   0.00876337      0.00450194   0.0224375 
 0.00719278  0.00676934   0.0158138   0.0044782       0.00630806   0.011484  
 0.0133911   0.0164393    0.00162767  0.0161445       0.00188172   0.0124033 
 0.0107277   0.0167289    0.0150532   0.016507    …   0.0106602    0.015633  
 0.00809611  0.00696858   0.0178111   0.00462718      0.00938611   0.0117599 
 0.0155917   0.0144396    0.00974111  0.0123784       0.00890559   0.0110218 
 0.0132811   0.00863529   0.011734    0.00704552      0.00837724   0.00740855
 0.018621    0.0127807   -0.0106548   0.0240958       0.0148448    0.00903233
 0.0130166   0.0110521    0.0087348   0.0105422   …   0.00757259   0.00987698
 0.00609657  0.0082923    0.0143675   0.00647175      0.0108519    0.0184329 
 0.0124777   0.00994313   0.0125661   

In [31]:
model.S

25-element Array{Float32,1}:
 8192.44 
 2144.0  
  830.729
 1145.8  
  904.974
 1126.62 
  686.182
  360.554
  364.215
  260.892
  241.281
  315.431
  292.136
  241.423
  227.429
  272.992
  227.568
  213.849
  195.05 
  177.823
  210.733
  192.379
  161.099
  120.392
  104.472

In [32]:
model.V

3706×25 Array{Float32,2}:
 0.0360245   0.00790537  0.0668403   …  -0.0249291    0.0174519 
 0.0247798   0.0151885   0.0199126      -0.00658329   0.011206  
 0.0303174   0.0135805   0.0307561      -0.00672107   0.0198856 
 0.032134    0.0117064   0.0534201       0.00161758  -0.00881031
 0.031527    0.00747639  0.0551341       0.0101183   -0.012524  
 0.034803    0.00473748  0.0705046   …  -0.0211418    0.00801113
 0.0304259   0.0081056   0.03053        -0.00417175   0.00722762
 0.0330957   0.00410418  0.0516199      -0.00581658   0.0120402 
 0.0285701   0.00698643  0.0228329       0.00798391   0.0266438 
 0.033364    0.00482974  0.0528213      -0.0225152    0.0404948 
 0.029748    0.00519264  0.0384952   …   0.00962256  -0.0158549 
 0.017696    0.0268795   0.00949011      0.00858581   0.0131488 
 0.0255312   0.0186715   0.0123975       0.00776442   0.0121873 
 ⋮                                   ⋱                          
 0.00118586  0.00259858  0.0040607       0.0133984    0.0144903 

In [33]:
similar_items(model, "Friday the 13th (1980)")

10-element Array{SubString{String},1}:
 "Friday the 13th (1980)"                                    
 "Amityville Horror, The (1979)"                             
 "Jaws 2 (1978)"                                             
 "Omen, The (1976)"                                          
 "Cujo (1983)"                                               
 "Friday the 13th Part 2 (1981)"                             
 "Pet Sematary (1989)"                                       
 "Stepford Wives, The (1975)"                                
 "First Blood (1982)"                                        
 "Nightmare on Elm Street Part 2: Freddy's Revenge, A (1985)"

In [34]:
@which similar_items(model, "Friday the 13th (1980)")

similar_items(model::IncrementalSVD.RatingsModel, item) at C:\Users\Ivan\.julia\v0.5\IncrementalSVD\src\util.jl:113

In [35]:
similar_items(model, "Citizen Kane (1941)")

10-element Array{SubString{String},1}:
 "Citizen Kane (1941)"                                                        
 "Chinatown (1974)"                                                           
 "Rear Window (1954)"                                                         
 "Vertigo (1958)"                                                             
 "Lawrence of Arabia (1962)"                                                  
 "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1963)"
 "M*A*S*H (1970)"                                                             
 "Casablanca (1942)"                                                          
 "Manchurian Candidate, The (1962)"                                           
 "Maltese Falcon, The (1941)"                                                 

In [36]:
similar_users(model,"3000")

10-element Array{SubString{String},1}:
 "3000"
 "2202"
 "5613"
 "4810"
 "5715"
 "4718"
 "244" 
 "4989"
 "3183"
 "5201"

In [37]:
# Stvarna ocjena je bila 4.0
get_predicted_rating(model, "3000", "Blade Runner (1982)")

4.205429f0

In [38]:
IncrementalSVD.get_predicted_rating(model, "3000", "Citizen Kane (1941)")

4.167101f0

## Tehnologija - github

Open Source!

[github]() je sustav za kolaborativan razvoj softvera - izlog!


## Julia i Jupyter

[Julia](http://julialang.org/) je novi programski jezik (evolucija) za BigData

* [JuliaBox](https://juliabox.com/)

[Jupyter](http://jupyter.org/) bilježnice:
 
 * tekst i programi u 40 jezika (Julia, Python, R)
 * HTML, knjiga (LaTeX, PDF)
 * prezentacija, `nbgrader`

## Hvala na pažnji

Pitanja?